/**
 * Export Service - Generates various export formats from session track data
 */

export interface TrackData {
  title: string;
  artist: string;
  album?: string;
  startTime: number;
  endTime: number;
  confidence: number;
  duration?: number;
}

export interface SessionData {
  id: string;
  sourceType: string;
  sourceUrl?: string;
  duration: number;
  createdAt: Date;
  tracks: TrackData[];
}

export type ExportFormat = 
  | 'json' 
  | 'csv' 
  | 'txt' 
  | 'youtube' 
  | 'cue' 
  | 'm3u' 
  | 'markdown';

/**
 * Format time in seconds to HH:MM:SS
 */
function formatTimestamp(seconds: number): string {
  const hrs = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  
  if (hrs > 0) {
    return `${hrs}:${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  }
  return `${mins}:${secs.toString().padStart(2, '0')}`;
}

/**
 * Format time for YouTube chapters (must start with 0:00)
 */
function formatYouTubeTimestamp(seconds: number): string {
  const hrs = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  
  if (hrs > 0) {
    return `${hrs}:${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  }
  return `${mins}:${secs.toString().padStart(2, '0')}`;
}

/**
 * Export to JSON format
 */
export function exportToJSON(session: SessionData): string {
  return JSON.stringify({
    sessionId: session.id,
    sourceType: session.sourceType,
    sourceUrl: session.sourceUrl,
    duration: session.duration,
    analyzedAt: session.createdAt.toISOString(),
    trackCount: session.tracks.length,
    tracks: session.tracks.map((t, i) => ({
      index: i + 1,
      title: t.title,
      artist: t.artist,
      album: t.album || null,
      startTime: t.startTime,
      endTime: t.endTime,
      duration: t.endTime - t.startTime,
      startTimestamp: formatTimestamp(t.startTime),
      endTimestamp: formatTimestamp(t.endTime),
      confidence: t.confidence,
    })),
  }, null, 2);
}

/**
 * Export to CSV format
 */
export function exportToCSV(session: SessionData): string {
  const headers = ['#', 'Title', 'Artist', 'Start Time', 'End Time', 'Duration', 'Confidence'];
  const rows = session.tracks.map((t, i) => [
    i + 1,
    `"${t.title.replace(/"/g, '""')}"`,
    `"${t.artist.replace(/"/g, '""')}"`,
    formatTimestamp(t.startTime),
    formatTimestamp(t.endTime),
    formatTimestamp(t.endTime - t.startTime),
    `${t.confidence}%`,
  ]);
  
  return [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
}

/**
 * Export to plain text format
 */
export function exportToText(session: SessionData): string {
  const lines = [
    `Tracklist - Analyzed ${session.createdAt.toLocaleDateString()}`,
    `Source: ${session.sourceUrl || session.sourceType}`,
    `Duration: ${formatTimestamp(session.duration)}`,
    `Tracks: ${session.tracks.length}`,
    '',
    '─'.repeat(60),
    '',
  ];
  
  session.tracks.forEach((t, i) => {
    lines.push(`${(i + 1).toString().padStart(2, '0')}. ${t.artist} - ${t.title}`);
    lines.push(`    ${formatTimestamp(t.startTime)} - ${formatTimestamp(t.endTime)} (${t.confidence}% match)`);
    lines.push('');
  });
  
  return lines.join('\n');
}

/**
 * Export to YouTube chapters format
 * Must include 0:00 as first timestamp
 */
export function exportToYouTubeChapters(session: SessionData): string {
  const lines: string[] = [];
  
  // YouTube requires first chapter at 0:00
  if (session.tracks.length > 0 && session.tracks[0].startTime > 0) {
    lines.push(`0:00 Intro`);
  }
  
  session.tracks.forEach((t) => {
    lines.push(`${formatYouTubeTimestamp(t.startTime)} ${t.artist} - ${t.title}`);
  });
  
  return lines.join('\n');
}

/**
 * Export to CUE sheet format
 */
export function exportToCue(session: SessionData, filename: string = 'audio'): string {
  const lines = [
    `REM Generated by Avine Audio Intelligence`,
    `REM Date: ${session.createdAt.toISOString()}`,
    `FILE "${filename}.mp3" MP3`,
  ];
  
  session.tracks.forEach((t, i) => {
    const mins = Math.floor(t.startTime / 60);
    const secs = Math.floor(t.startTime % 60);
    const frames = Math.floor((t.startTime % 1) * 75); // CUE uses 75 frames per second
    
    lines.push(`  TRACK ${(i + 1).toString().padStart(2, '0')} AUDIO`);
    lines.push(`    TITLE "${t.title}"`);
    lines.push(`    PERFORMER "${t.artist}"`);
    lines.push(`    INDEX 01 ${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}:${frames.toString().padStart(2, '0')}`);
  });
  
  return lines.join('\n');
}

/**
 * Export to M3U playlist format
 */
export function exportToM3U(session: SessionData): string {
  const lines = [
    '#EXTM3U',
    `#PLAYLIST:Avine Analysis - ${session.createdAt.toLocaleDateString()}`,
  ];
  
  session.tracks.forEach((t) => {
    const duration = t.endTime - t.startTime;
    lines.push(`#EXTINF:${duration},${t.artist} - ${t.title}`);
    // Note: M3U typically needs file paths or URLs, but we output searchable info
    lines.push(`# Search: ${t.artist} - ${t.title}`);
  });
  
  return lines.join('\n');
}

/**
 * Export to Markdown format
 */
export function exportToMarkdown(session: SessionData): string {
  const lines = [
    `# Tracklist`,
    '',
    `> Analyzed: ${session.createdAt.toLocaleDateString()}`,
    `> Source: ${session.sourceUrl || session.sourceType}`,
    `> Duration: ${formatTimestamp(session.duration)}`,
    '',
    '| # | Artist | Title | Time | Confidence |',
    '|---|--------|-------|------|------------|',
  ];
  
  session.tracks.forEach((t, i) => {
    const time = `${formatTimestamp(t.startTime)} - ${formatTimestamp(t.endTime)}`;
    lines.push(`| ${i + 1} | ${t.artist} | ${t.title} | ${time} | ${t.confidence}% |`);
  });
  
  return lines.join('\n');
}

/**
 * Main export function - generates output in specified format
 */
export function exportSession(session: SessionData, format: ExportFormat, options?: { filename?: string }): string {
  switch (format) {
    case 'json':
      return exportToJSON(session);
    case 'csv':
      return exportToCSV(session);
    case 'txt':
      return exportToText(session);
    case 'youtube':
      return exportToYouTubeChapters(session);
    case 'cue':
      return exportToCue(session, options?.filename);
    case 'm3u':
      return exportToM3U(session);
    case 'markdown':
      return exportToMarkdown(session);
    default:
      throw new Error(`Unsupported export format: ${format}`);
  }
}

/**
 * Get MIME type for format
 */
export function getMimeType(format: ExportFormat): string {
  switch (format) {
    case 'json':
      return 'application/json';
    case 'csv':
      return 'text/csv';
    case 'txt':
      return 'text/plain';
    case 'youtube':
      return 'text/plain';
    case 'cue':
      return 'application/x-cue';
    case 'm3u':
      return 'audio/x-mpegurl';
    case 'markdown':
      return 'text/markdown';
    default:
      return 'text/plain';
  }
}

/**
 * Get file extension for format
 */
export function getFileExtension(format: ExportFormat): string {
  switch (format) {
    case 'json':
      return 'json';
    case 'csv':
      return 'csv';
    case 'txt':
      return 'txt';
    case 'youtube':
      return 'txt';
    case 'cue':
      return 'cue';
    case 'm3u':
      return 'm3u';
    case 'markdown':
      return 'md';
    default:
      return 'txt';
  }
}
